seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 10
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 1
    time: 1-00:00
    

# experiment random configs
  
random:
  samples: 30
  seed: 453

  graphgym.seed:
    seed: 142
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 144
    type: loguniform
    min: 9e-5
    max: 3e-3

  graphgym.optim.weight_decay:
    seed: 413
    type: loguniform
    min: 1e-6
    max: 2e-2

  dims_per_head:
    seed: 13
    type: randint
    min: 6
    max: 27

  graphgym.graphormer.num_layers:
    seed: 357
    type: randint
    min: 9
    max: 17

  graphgym.graphormer.attention_dropout:
    seed: 661
    type: uniform
    min: 0.25
    max: 0.5

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-TUDataset
      name: ENZYMES
      task: graph
      task_type: classification
      transductive: false
      split_mode: cv-stratifiedkfold-10
      split_index: 0
      node_encoder: true
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_bn: false
      edge_encoder: false

    train:
      mode: custom
      batch_size: 32
      eval_period: 1

    posenc_GraphormerBias:
      enable: true
      node_degrees_only: false
      directed_graphs: false
      has_edge_attr: false
      num_spatial_types: 23
      num_in_degrees: 9
      num_out_degrees: ${config.graphgym.posenc_GraphormerBias.num_in_degrees}

    model:
      type: Graphormer
      loss_fun: cross_entropy
      graph_pooling: graph_token

    graphormer:
      embed_dim: 0  # determined using num_heads and dims_per_head
      input_dropout: 0.0
      num_heads: 8
      dropout: 0.03
      mlp_dropout: 0.01

    gnn:
      head: graphormer_graph
      layers_pre_mp: 0
      dim_inner: 0  # determined using num_heads and dims_per_head
      layers_post_mp: 1

    optim:
      optimizer: adamW
      max_epoch: 500
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 10
      min_lr: 1.0e-5
      early_stopping: true
      early_stopping_patience: 50
      early_stopping_delta_e: 0.02
      early_stopping_warmup: 50
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      
    attack:
      enable: false
