seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 2
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 24G
    cpus-per-task: 2
    time: 1-00:00
    

grid:

  graphgym.attack.transfer.perturbation_path:
    type: choice
    options:
      - '/<your-saved-path>/perturbations/UPFD_gos_bert/GRIT'
      - '/<your-saved-path>/perturbations/UPFD_gos_bert/SAN'
      - '/<your-saved-path>/perturbations/UPFD_gos_bert/GCN'
      - '/<your-saved-path>/perturbations/UPFD_gos_bert/Graphormer'
      - '/<your-saved-path>/perturbations/UPFD_gos_bert/GPS'
      - '/<your-saved-path>/perturbations/UPFD_gos_bert/Polynormer'

# experiment fixed configs

fixed:

  graphgym:

    seed: 15

    accelerator: auto

    out_dir: configs_seml/results

    pretrained:
      dir: '/<your-saved-path>/models/Graphormer/UPFD_gos_bert/0'
      finetune: false

    posenc_GraphormerBias:
      dim_pe: 0
      directed_graphs: false
      enable: true
      has_edge_attr: false
      node_degrees_only: false
      num_in_degrees: 21
      num_out_degrees: 21
      num_spatial_types: 8

    attack:
      transfer:
        enable: true
      enable: true
      num_attacked_graphs: 0
      skip_incorrect_graph_classification: false
      log_progress: false
      load_best_model: false
      split: test
      prediction_level: graph
      remove_isolated_components: true
      run_random_baseline: false
      is_undirected: true
      root_node_idx: 0
      node_injection:
        enable: true
        from_train: true
        from_val: true
        from_test: true
        allow_existing_graph_pert: false
        include_root_nodes: false
        sample_only_trees: true

    # copied from pre-trained model

    benchmark: false
    best_by_loss: false
    bn:
      eps: 1.0e-05
      mom: 0.1
    custom_metrics: []
    dataset:
      cache_load: false
      cache_save: false
      dir: ./datasets
      edge_dim: 128
      edge_encoder: false
      edge_encoder_bn: true
      edge_encoder_name: Bond
      edge_encoder_num_types: 0
      edge_message_ratio: 0.8
      edge_negative_sampling_ratio: 1.0
      edge_train_mode: all
      encoder: true
      encoder_bn: true
      encoder_dim: 128
      encoder_name: db
      format: PyG-UPFD
      infer_link_label: null
      label_column: none
      label_table: none
      location: local
      name: gossipcop-bert
      node_encoder: true
      node_encoder_bn: false
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_num_types: 0
      pe_transform_on_the_fly: false
      remove_feature: false
      resample_disjoint: false
      resample_negative: false
      shuffle_split: true
      slic_compactness: 10
      split:
      - 0.8
      - 0.1
      - 0.1
      split_dir: ./splits
      split_index: 0
      split_mode: standard
      task: graph
      task_type: classification_binary
      to_undirected: false
      transductive: false
      transform: none
      tu_simple: true
    devices: 1
    example_arg: example
    example_group:
      example_arg: example
    gnn:
      act: relu
      agg: add
      att_final_linear: false
      att_final_linear_bn: false
      att_heads: 1
      batchnorm: true
      clear_feature: true
      dim_inner: 30
      dropout: 0.0
      head: graphormer_graph
      keep_edge: 0.5
      l2norm: true
      layer_type: generalconv
      layers_mp: 2
      layers_post_mp: 1
      layers_pre_mp: 0
      msg_direction: single
      normalize_adj: false
      residual: false
      self_msg: concat
      skip_every: 1
      stage_type: stack
    gpu_mem: false
    graphormer:
      attention_dropout: 0.3821419034723292
      dropout: 0.06887303117315342
      embed_dim: 30
      input_dropout: 0.008648277863293575
      mlp_dropout: 0.05367421263138533
      num_heads: 3
      num_layers: 8
      use_graph_token: true
    gt:
      attn:
        O_e: true
        act: relu
        clamp: 5.0
        deg_scaler: true
        edge_enhance: true
        full_attn: true
        norm_e: true
        use_bias: false
      attn_dropout: 0.0
      batch_norm: true
      bigbird:
        add_cross_attention: false
        attention_type: block_sparse
        block_size: 3
        chunk_size_feed_forward: 0
        hidden_act: relu
        is_decoder: false
        layer_norm_eps: 1.0e-06
        max_position_embeddings: 128
        num_random_blocks: 3
        use_bias: false
      bn_momentum: 0.1
      bn_no_runner: false
      dim_hidden: 64
      dropout: 0.0
      full_graph: true
      gamma: 1.0e-05
      gamma_learnable: false
      layer_norm: false
      layer_type: SANLayer
      layers: 3
      n_heads: 8
      pna_degrees: []
      residual: true
      update_e: true
    mem:
      inplace: false
    metric_agg: argmax
    metric_best: accuracy
    model:
      edge_decoding: dot
      graph_pooling: graph_token
      loss_fun: cross_entropy
      match_upper: true
      size_average: mean
      thresh: 0.5
      type: Graphormer
    name_tag: ''
    num_threads: 6
    num_workers: 0
    optim:
      base_lr: 0.00037486491123483095
      batch_accumulation: 1
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      early_stopping: true
      early_stopping_delta_e: 0.01
      early_stopping_patience: 30
      early_stopping_warmup: 30
      lr_decay: 0.1
      max_epoch: 100
      min_lr: 0.0
      momentum: 0.9
      num_warmup_epochs: 5
      optimizer: adamW
      reduce_factor: 0.1
      schedule_patience: 10
      scheduler: cosine_with_warmup
      steps:
      - 30
      - 60
      - 90
      weight_decay: 1.3734889554522809e-05
    posenc_ElstaticSE:
      dim_pe: 16
      enable: false
      kernel:
        times: []
        times_func: range(10)
      layers: 3
      model: none
      n_heads: 4
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none
    posenc_EquivStableLapPE:
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      enable: false
      raw_norm_type: none
    posenc_HKdiagSE:
      dim_pe: 16
      enable: false
      kernel:
        times: []
        times_func: ''
      layers: 3
      model: none
      n_heads: 4
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none
    posenc_LapPE:
      dim_pe: 16
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      enable: false
      layers: 3
      model: none
      n_heads: 4
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none
    posenc_RRWP:
      enable: false
      ksteps: 21
      w_add_dummy_edge: false
    posenc_RWSE:
      dim_pe: 16
      enable: false
      kernel:
        times: []
        times_func: ''
      layers: 3
      model: none
      n_heads: 4
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none
    posenc_SignNet:
      dim_pe: 16
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      enable: false
      layers: 3
      model: none
      n_heads: 4
      pass_as_var: false
      phi_hidden_dim: 64
      phi_out_dim: 4
      post_layers: 0
      raw_norm_type: none
    posenc_WLapPE:
      dim_pe: 16
      eigen:
        eigvec_norm: L2
 
        laplacian_norm: sym
        max_freqs: 10
 
      enable: false
      layers: 3
      model: none
      n_heads: 4
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none
    print: both
    robustness_unit_test:
      enable: false
      load_best_model: true
    round: 5
    run_multiple_splits: []
    share:
      dim_in: 1
      dim_out: 1
      num_splits: 1
    tensorboard_agg: true
    tensorboard_each_run: false
    train:
      auto_resume: false
      batch_size: 16
      ckpt_best: true
      ckpt_clean: true
      ckpt_period: 100
      enable_ckpt: true
      epoch_resume: -1
      eval_period: 1
      homophily_regularization: 0.0
      homophily_regularization_gt_weight: 1.0
      iter_per_epoch: 32
      mode: custom
      neighbor_sizes:
      - 20
      - 15
      - 10
      - 5
      node_per_graph: 32
      radius: extend
      sample_node: false
      sampler: full_batch
      skip_train_eval: false
      walk_length: 4
    val:
      node_per_graph: 32
      radius: extend
      sample_node: false
      sampler: full_batch
    view_emb: false
    wandb:
      entity: graph-transformer-robustness
      name: ''
      project: gtblueprint
      use: false
