seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 10
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 2
    time: 1-00:00
    

# experiment random configs
  
random:
  samples: 30
  seed: 453

  graphgym.seed:
    seed: 453
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 1454
    type: loguniform
    min: 9e-5
    max: 4e-3

  graphgym.optim.weight_decay:
    seed: 509
    type: loguniform
    min: 9e-7
    max: 1e-2

  dims_per_head:
    seed: 204
    type: randint
    min: 8
    max: 27

  graphgym.gnn.dropout:
    seed: 342
    type: uniform
    min: 0.0
    max: 0.5

  graphgym.gt.dropout:
    seed: 131
    type: uniform
    min: 0.0
    max: 0.05

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-TUDataset
      name: ENZYMES
      task: graph
      task_type: classification
      transductive: false
      split_mode: cv-stratifiedkfold-10
      split_index: 0
      node_encoder: true
      node_encoder_name: LinearNode
      node_encoder_bn: false
      edge_encoder: false

    train:
      mode: custom
      batch_size: 32
      eval_period: 1

    model:
      type: WeightedPolynormer
      loss_fun: cross_entropy

    gt:
      n_heads: 8
      layers: 2
      dim_hidden: 0  # determined using num_heads and dims_per_head
      polynormer:
        dropout_node_input: 0.0
        local_pre_layer_norm: false
        beta: -1.0
        qk_shared: true

    gnn:
      head: weighted_add_pool_graph
      layers_pre_mp: 0
      dim_inner: 0  # determined using num_heads and dims_per_head
      att_heads: 8
      layers_mp: 6
      layers_post_mp: 3

    optim:
      optimizer: adamW
      max_epoch: 500
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 7
      min_lr: 1.0e-5
      early_stopping: true
      early_stopping_patience: 70
      early_stopping_delta_e: 0.02
      early_stopping_warmup: 70
      clip_grad_norm: false
      
    attack:
      enable: false
