seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 16G
    cpus-per-task: 1
    time: 1-00:00

fixed:

  graphgym:
    accelerator: auto
    attack:
      enable: false
    benchmark: false
    best_by_loss: false
    bn:
      eps: 1.0e-05
      mom: 0.1
    dataset:
      dir: ./datasets
      edge_encoder: true
      edge_encoder_bn: false
      edge_encoder_name: WeightedSANDummyEdge
      format: PyG-UPFD
      name: gossipcop-bert
      node_encoder: true
      node_encoder_bn: false
      node_encoder_name: WLapPE
      split_mode: standard
      task: graph
      task_type: classification_binary
      transductive: false
    gnn:
      dim_inner: 80
      dropout: 0.0
      head: weighted_mean_pool_graph
      layers_post_mp: 1
      layers_pre_mp: 0
    gt:
      attn:
        O_e: true
        act: relu
        clamp: 5.0
        deg_scaler: true
        edge_enhance: true
        full_attn: true
        norm_e: true
        use_bias: false
      attn_dropout: 0.0
      batch_norm: true
      bn_momentum: 0.1
      bn_no_runner: false
      dim_hidden: 80
      dropout: 0.017311995356348094
      full_graph: true
      gamma: 0.00428447568810894
      gamma_learnable: false
      layer_norm: false
      layer_type: SANLayer
      layers: 3
      n_heads: 8
      pna_degrees: []
      residual: true
      update_e: true
      wsan_add_dummy_edges: false
    metric_agg: argmax
    metric_best: accuracy
    model:
      loss_fun: cross_entropy
      type: WeightedSANTransformer
    optim:
      base_lr: 0.0005413687562373416
      batch_accumulation: 1
      clip_grad_norm: false
      clip_grad_norm_value: 1.0
      early_stopping: true
      early_stopping_delta_e: 0.03
      early_stopping_patience: 40
      early_stopping_warmup: 30
      lr_decay: 0.1
      max_epoch: 250
      min_lr: 0.0
      momentum: 0.9
      num_warmup_epochs: 50
      optimizer: adam
      reduce_factor: 0.5
      schedule_patience: 20
      scheduler: reduce_on_plateau
      steps:
      - 30
      - 60
      - 90
      weight_decay: 0.0
    posenc_WLapPE:
      dim_pe: 20
      eigen:
        eigvec_norm: L2
        eps_repeated_eigenvalue: 1.0e-06
        laplacian_norm: sym
        max_freqs: 24
        nia_pert: half_weight
      enable: true
      layers: 2
      model: none
      n_heads: 5
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none
    seed: 6718
    train:
      auto_resume: false
      batch_size: 32
      ckpt_best: true
      ckpt_clean: true
      ckpt_period: 100
      enable_ckpt: true
      epoch_resume: -1
      eval_period: 1
      homophily_regularization: 0.0
      homophily_regularization_gt_weight: 1.0
      iter_per_epoch: 32
      mode: custom
      neighbor_sizes:
      - 20
      - 15
      - 10
      - 5
      node_per_graph: 32
      radius: extend
      sample_node: false
      sampler: full_batch
      skip_train_eval: false
      walk_length: 4
