seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 6
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 8
    time: 1-00:00

# Hyperparameter search

random:
  samples: 30
  seed: 7537

  graphgym.seed:
    seed: 8286
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 126
    type: loguniform
    min: 6.0e-4
    max: 5.0e-3

  dims_per_head:
    seed: 43514
    type: randint
    min: 4
    max: 9

  graphgym.gt.layers:
    seed: 11762
    type: randint
    min: 12
    max: 17

  graphgym.gnn.layers_post_mp:
    seed: 191
    type: choice
    options:
      - 1
      - 2

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false

    train:
      mode: custom
      eval_period: 1
      batch_size: 64

    model:
      type: GPSModel
      loss_fun: weighted_cross_entropy

    posenc_WLapPE:
      enable: true
      dim_pe: 16
      layers: 2
      model: DeepSet
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none

    gt:
      layer_type: WeightedGCN+Transformer
      dim_hidden: 0  # determined using num_heads and dims_per_head
      layer_norm: false
      batch_norm: true
      dropout: 0.05
      attn_dropout: 0.4
      n_heads: 8

    gnn:
      batchnorm: true
      act: relu
      head: inductive_node
      layers_pre_mp: 0
      dim_inner: 0  # determined using num_heads and dims_per_head

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      weight_decay: 1.0e-8
      max_epoch: 150
      scheduler: cosine_with_warmup
      num_warmup_epochs: 5
      early_stopping: true
      early_stopping_patience: 40
      early_stopping_delta_e: 0.0
      early_stopping_warmup: 20

    attack:
      enable: false
