seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 12G
    cpus-per-task: 4
    time: 1-00:00

# experiment fixed configs

fixed:

  graphgym:

    seed: 42

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false
      edge_encoder: True
      edge_encoder_name: WeightedDummyEdge
      edge_encoder_bn: False

    train:
      mode: custom
      eval_period: 1
      batch_size: 16

    model:
      type: GPSModel
      loss_fun: weighted_cross_entropy

    posenc_WLapPE:
      enable: true
      dim_pe: 16
      layers: 2
      model: DeepSet
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none

    gt:
      layer_type: WeightedGatedGCN+Transformer
      layers: 16
      dim_hidden: 48
      layer_norm: false
      batch_norm: true
      dropout: 0.1
      attn_dropout: 0.5
      n_heads: 8

    gnn:
      batchnorm: true
      act: relu
      head: inductive_node
      layers_pre_mp: 0
      layers_post_mp: 3
      dim_inner: 48

    optim:
      clip_grad_norm: true
      optimizer: adamW
      weight_decay: 1.0e-5
      max_epoch: 100
      scheduler: cosine_with_warmup
      base_lr: 0.0005
      num_warmup_epochs: 5
      early_stopping: true
      early_stopping_patience: 40
      early_stopping_delta_e: 0.0
      early_stopping_warmup: 20

    attack:
      enable: false
