seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 5
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 2
    time: 1-00:00
    

# experiment random configs

random:
  samples: 30
  seed: 425

  graphgym.seed:
    seed: 835
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 1.0e-5
    max: 3.0e-2

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 5.0e-7
    max: 1.0e-1

  graphgym.posenc_WLapPE.eigen.max_freqs:
    seed: 135
    type: randint
    min: 5
    max: 20

  dims_per_head:
    seed: 13094
    type: randint
    min: 3
    max: 13

  graphgym.gt.layers:
    seed: 11762
    type: randint
    min: 3
    max: 17

  graphgym.gt.dropout: 
    seed: 326
    type: uniform
    min: 0.0
    max: 0.15
  
  graphgym.gt.attn_dropout:
    seed: 2526
    type: uniform
    min: 0.0
    max: 0.5
  
  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 3

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-TUDataset
      name: ENZYMES
      task: graph
      task_type: classification
      transductive: false
      split_mode: cv-stratifiedkfold-10
      split_index: 0
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false
      edge_encoder: true
      edge_encoder_name: WeightedDummyEdge
      edge_encoder_bn: false

    train:
      mode: custom
      eval_period: 1
      batch_size: 32

    model:
      type: GPSModel
      loss_fun: cross_entropy

    posenc_WLapPE:
      enable: true
      dim_pe: 16
      layers: 2
      model: DeepSet
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none

    gt:
      layer_type: WeightedGatedGCN+Transformer
      dim_hidden: 0  # determined later
      layer_norm: false
      batch_norm: true
      n_heads: 8

    gnn:
      batchnorm: true
      act: relu
      head: weighted_add_pool_graph
      layers_pre_mp: 0
      dim_inner: 0  # determined later

    optim:
      optimizer: adamW
      max_epoch: 500
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 7
      min_lr: 1.0e-5
      early_stopping: true
      early_stopping_patience: 50
      early_stopping_delta_e: 0.02
      early_stopping_warmup: 50
      clip_grad_norm: true
      clip_grad_norm_value: 5.0

    attack:
      enable: false
