seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 6
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 2
    time: 1-00:00
    

grid:

  graphgym.attack.transfer.perturbation_path:
    type: choice
    options:
      - '/<your-saved-path>/perturbations/ENZYMES/GRIT'
      - '/<your-saved-path>/perturbations/ENZYMES/SAN'
      - '/<your-saved-path>/perturbations/ENZYMES/GCN'
      - '/<your-saved-path>/perturbations/ENZYMES/Graphormer'
      - '/<your-saved-path>/perturbations/ENZYMES/GPS'
      - '/<your-saved-path>/perturbations/ENZYMES/Polynormer'

# experiment fixed configs

fixed:

  graphgym:

    seed: 15

    out_dir: configs_seml/results

    pretrained:
      dir: '/<your-saved-path>/models/GPS/ENZYMES/0'
      finetune: false

    attack:
      transfer:
        enable: true
      enable: true
      num_attacked_graphs: 0
      skip_incorrect_graph_classification: false
      log_progress: false
      load_best_model: false
      split: test
      prediction_level: graph
      remove_isolated_components: false
      run_random_baseline: false
      is_undirected: true
      node_injection:
        enable: false
  
    # copied from pre-trained model
    accelerator: cuda
    bn:
      eps: 1.0e-05
      mom: 0.1
    dataset:
      cache_load: false
      cache_save: false
      dir: ./datasets
      edge_dim: 128
      edge_encoder: true
      edge_encoder_bn: false
      edge_encoder_name: WeightedDummyEdge
      edge_encoder_num_types: 0
      edge_message_ratio: 0.8
      edge_negative_sampling_ratio: 1.0
      edge_train_mode: all
      encoder: true
      encoder_bn: true
      encoder_dim: 128
      encoder_name: db
      format: PyG-TUDataset
      infer_link_label: None
      label_column: none
      label_table: none
      location: local
      name: ENZYMES
      node_encoder: true
      node_encoder_bn: false
      node_encoder_name: WLapPE
      node_encoder_num_types: 0
      pe_transform_on_the_fly: false
      remove_feature: false
      resample_disjoint: false
      resample_negative: false
      shuffle_split: true
      slic_compactness: 10
      split:
      - 0.8
      - 0.1
      - 0.1
      split_dir: ./splits
      split_index: 0
      split_mode: cv-stratifiedkfold-10
      task: graph
      task_type: classification
      to_undirected: false
      transductive: false
      transform: none
      tu_simple: true
    gnn:
      act: relu
      agg: add
      att_final_linear: false
      att_final_linear_bn: false
      att_heads: 1
      batchnorm: true
      clear_feature: true
      dim_inner: 96
      dropout: 0.0
      head: weighted_add_pool_graph
      keep_edge: 0.5
      l2norm: true
      layer_type: generalconv
      layers_mp: 2
      layers_post_mp: 3
      layers_pre_mp: 0
      msg_direction: single
      normalize_adj: false
      residual: false
      self_msg: concat
      skip_every: 1
      stage_type: stack
    gt:
      attn:
        O_e: true
        act: relu
        clamp: 5.0
        deg_scaler: true
        edge_enhance: true
        full_attn: true
        norm_e: true
        use_bias: false
      attn_dropout: 0.3517881962110635
      batch_norm: true
      bn_momentum: 0.1
      bn_no_runner: false
      dim_hidden: 96
      dropout: 0.08562637312017338
      full_graph: true
      gamma: 1.0e-05
      gamma_learnable: false
      layer_norm: false
      layer_type: WeightedGatedGCN+Transformer
      layers: 7
      n_heads: 8
      pna_degrees: []
      residual: true
      update_e: true
    metric_agg: argmax
    metric_best: accuracy
    model:
      edge_decoding: dot
      graph_pooling: add
      loss_fun: cross_entropy
      match_upper: true
      size_average: mean
      thresh: 0.5
      type: GPSModel
    posenc_WLapPE:
      dim_pe: 16
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 18
      enable: true
      layers: 2
      model: DeepSet
      n_heads: 4
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none
      w_add_dummy_edge: true
