seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 3
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 16G
    cpus-per-task: 1
    time: 1-00:00

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: politifact-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_bn: false

    posenc_GraphormerBias:
      enable: true
      node_degrees_only: false
      directed_graphs: false
      has_edge_attr: false
      num_out_degrees: ${config.graphgym.posenc_GraphormerBias.num_in_degrees}
      # next 2 only matter for attack, set to fixed false
       
 

    train:
      mode: custom
      eval_period: 1
      # hyperparameter search, no need to save the models
      enable_ckpt: false
      batch_size: 16

    model:
      type: Graphormer
      loss_fun: cross_entropy
      graph_pooling: graph_token

    graphormer:
      dropout: 0.0
      # TODO: look at hyperparameters in papers -> often set quite high (up to 0.5)
      attention_dropout: 0.0
      mlp_dropout: 0.0
      input_dropout: 0.0
      embed_dim: 0  # determined using num_heads and dims_per_head

    gnn:
      layers_pre_mp: 0
      head: graphormer_graph
      dim_inner: 0 # determined using num_heads and dims_per_head

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 300
      scheduler: cosine_with_warmup
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

    attack:
      enable: false

# experiment random configs

random:
  samples: 300
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 1e-4
    max: 2e-1

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1e-5
    max: 1e-1

  graphgym.graphormer.num_heads:
    seed: 13094
    type: randint
    min: 1
    max: 11

  dims_per_head:
    seed: 13094
    type: randint
    min: 4
    max: 50

  graphgym.graphormer.num_layers:
    seed: 357
    type: randint
    min: 1
    max: 7

  graphgym.posenc_GraphormerBias.num_spatial_types:
    seed: 2846
    type: randint
    min: 6
    max: 15

  graphgym.posenc_GraphormerBias.num_in_degrees:
    seed: 647
    type: randint
    min: 8
    max: 41
  
  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2
      - 3

  graphgym.optim.num_warmup_epochs:
    seed: 3976
    type: choice
    options:
      - 5
      - 10
      - 20
