seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 12G
    cpus-per-task: 4
    time: 1-00:00

# experiment fixed configs - taken from benchmarking paper

fixed:

  graphgym:

    seed: 42

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: LinearNode
      node_encoder_bn: false
      edge_encoder: false

    train:
      mode: custom
      batch_size: 128
      eval_period: 1

    model:
      type: gnn
      loss_fun: weighted_cross_entropy

    gnn:
      layer_type: gatconvweighted
      stage_type: skipsum
      head: inductive_node
      agg: mean
      dropout: 0.0
      layers_pre_mp: 0
      layers_mp: 16
      layers_post_mp: 2
      att_heads: 8
      batchnorm: true
      normalize_adj: false
      dim_inner: 176

    optim:
      optimizer: adam
      weight_decay: 0.0
      base_lr: 0.001
      max_epoch: 150
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 5
      min_lr: 1.0e-5
      clip_grad_norm: false
      early_stopping: true
      early_stopping_patience: 25
      early_stopping_delta_e: 0.01
      early_stopping_warmup: 40

    attack:
      enable: false
