### Example:
# just take a config from `configs_seml/configs` and only copy the graphgym section
# then make sure that all the sampled parameters are included with a given value
# since we are using seml to sample 
# (and these local debug configs are meant to be executed without seml)

graphgym:

  seed: 42
  accelerator: cuda
  out_dir: configs_seml/results
  metric_best: accuracy
  metric_agg: argmax
  tensorboard_each_run: false

  dataset:
    format: PyG-UPFD
    name: politifact-bert
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false

  train:
    mode: custom
    eval_period: 1
    batch_size: 16

  model:
    type: gnn
    loss_fun: cross_entropy

  gnn:
    dim_inner: 80
    layers_pre_mp: 0
    layers_mp: 2
    head: weighted_mean_pool_graph
    layers_post_mp: 2
    layer_type: gcnconvweighted
    stage_type: stack
    batchnorm: true
    act: relu
    dropout: 0.0

  optim:
    base_lr: 1e-5
    weight_decay: 1e-5
    clip_grad_norm: true
    clip_grad_norm_value: 5.0
    optimizer: adamW
    max_epoch: 300
    scheduler: cosine_with_warmup
    num_warmup_epochs: 15
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.04
    early_stopping_warmup: 30

  attack:
    enable: false
