seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 16G
    cpus-per-task: 4
    time: 1-00:00

# experiment fixed configs

fixed:

  graphgym:

    accelerator: auto
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-RobustnessUnitTest
      name: cora_ml
      task: node
      task_type: classification
      transductive: true
      split_mode: standard
      split_index: 0
      node_encoder: true
      node_encoder_name: LinearNode+WeightedRRWPLinear
      node_encoder_bn: false

    posenc_RRWP:
        enable: true
        w_add_dummy_edge: true

    train:
      mode: custom
      batch_size: 1
      eval_period: 1
      ckpt_best: true
      enable_ckpt: true

    model:
      type: GritTransformer
      loss_fun: cross_entropy

    gt:
      dim_hidden: 0
      layer_norm: false
      batch_norm: true
      bn_no_runner: false
      bn_momentum: 0.1
      update_e: true
      attn:
        deg_scaler: true
        use_bias: false
        clamp: 5.
        act: relu
        full_attn: true
        norm_e: true
        O_e: true
        edge_enhance: true

    gnn:
      dim_inner: 0
      head: node
      layers_pre_mp: 0
      layers_post_mp: 1

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      weight_decay: 0.0001
      max_epoch: 200
      scheduler: cosine_with_warmup
      num_warmup_epochs: 10
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

# experiment random configs

random:
  samples: 300
  seed: 246

  graphgym.seed:
    seed: 643
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2457
    type: loguniform
    min: 8e-4
    max: 1e-2

  graphgym.gt.layers:
    seed: 2564
    type: randint
    min: 2
    max: 5

  graphgym.gt.n_heads:
    seed: 620
    type: randint
    min: 2
    max: 8

  dims_per_head:
    seed: 3237
    type: randint
    min: 2
    max: 8

  graphgym.gt.dropout:
    seed: 87259
    type: uniform
    min: 0.0
    max: 0.2

  graphgym.gt.attn_dropout:
    seed: 863
    type: uniform
    min: 0.1
    max: 0.6

  graphgym.posenc_RRWP.ksteps:
    seed: 1143
    type: randint
    min: 10
    max: 25

  graphgym.train.homophily_regularization: 
    seed: 883
    type: uniform
    min: 0.0
    max: 5.0

  graphgym.train.homophily_regularization_gt_weight:
    seed: 8462
    type: uniform
    min: 1.0
    max: 10.0
