seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 16G
    cpus-per-task: 1
    time: 1-00:00

fixed:

  graphgym:

    accelerator: auto
    attack:
      enable: false
    benchmark: false
    best_by_loss: false
    bn:
      eps: 1.0e-05
      mom: 0.1
    dataset:
      dir: ./datasets
      format: PyG-UPFD
      name: gossipcop-bert
      node_encoder: true
      node_encoder_bn: false
      node_encoder_name: LinearNode+WeightedRRWPLinear
      edge_encoder: false
      split_mode: standard
      task: graph
      task_type: classification_binary
      transductive: false
    gnn:
      act: relu
      batchnorm: true
      dim_inner: 18
      dropout: 0.0
      head: weighted_add_pool_graph
      layers_post_mp: 1
      layers_pre_mp: 0
    gt:
      attn:
        O_e: true
        act: relu
        clamp: 5.0
        deg_scaler: true
        edge_enhance: true
        full_attn: true
        norm_e: true
        use_bias: false
      attn_dropout: 0.29285307330003657
      batch_norm: true
      bn_momentum: 0.1
      bn_no_runner: false
      dim_hidden: 18
      dropout: 0.055525926216241285
      full_graph: true
      layer_norm: false
      layers: 6
      n_heads: 6
      residual: true
      update_e: true
    metric_agg: argmax
    metric_best: accuracy
    model:
      loss_fun: cross_entropy
      type: GritTransformer
    optim:
      base_lr: 0.0022391067229686553
      batch_accumulation: 1
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      early_stopping: true
      early_stopping_delta_e: 0.01
      early_stopping_patience: 30
      early_stopping_warmup: 20
      lr_decay: 0.1
      max_epoch: 100
      min_lr: 0.0
      momentum: 0.9
      num_warmup_epochs: 5
      optimizer: adamW
      reduce_factor: 0.1
      schedule_patience: 10
      scheduler: cosine_with_warmup
      steps:
      - 30
      - 60
      - 90
      weight_decay: 1.2021270434702793e-08
    posenc_RRWP:
      enable: true
      ksteps: 6
      w_add_dummy_edge: true
    seed: 2327
    train:
      batch_size: 16
      ckpt_best: true
      enable_ckpt: true
      eval_period: 1
      mode: custom
