seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 3
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 2
    time: 1-00:00
    

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-TUDataset
      name: reddit_threads
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: cv-stratifiedkfold-8
      split_index: 6
      split_dir: datasets/splits
      node_encoder: true
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_bn: false
      edge_encoder: false

    train:
      mode: custom
      eval_period: 1
      enable_ckpt: true
      batch_size: 64  # very small graphs

    posenc_GraphormerBias:
      enable: true
      node_degrees_only: false
      directed_graphs: false
      has_edge_attr: false
      num_out_degrees: ${config.graphgym.posenc_GraphormerBias.num_in_degrees}

    model:
      type: Graphormer
      loss_fun: cross_entropy
      graph_pooling: graph_token

    graphormer:
      embed_dim: 0  # determined using num_heads and dims_per_head
      input_dropout: 0.0
      num_heads: 8

    gnn:
      layers_pre_mp: 0
      head: graphormer_graph
      dim_inner: 0 # determined using num_heads and dims_per_head

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 30
      scheduler: cosine_with_warmup
      early_stopping: true
      early_stopping_patience: 7
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 3
      num_warmup_epochs: 1

    attack:
      enable: false

# experiment random configs

random:
  samples: 30
  seed: 425

  graphgym.seed:
    seed: 835
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 4e-6
    max: 1e-1

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1e-8
    max: 1e-2

  dims_per_head:
    seed: 13094
    type: randint
    min: 3
    max: 17

  graphgym.graphormer.num_layers:
    seed: 357
    type: randint
    min: 2
    max: 13

  graphgym.graphormer.dropout:
    seed: 961
    type: uniform
    min: 0.0
    max: 0.1
  
  graphgym.graphormer.attention_dropout:
    seed: 661
    type: uniform
    min: 0.1
    max: 0.5

  graphgym.graphormer.mlp_dropout:
    seed: 241
    type: uniform
    min: 0.0
    max: 0.1

  graphgym.posenc_GraphormerBias.num_in_degrees:
    seed: 647
    type: randint
    min: 5
    max: 50

  graphgym.posenc_GraphormerBias.num_spatial_types:
    seed: 5113
    type: randint
    min: 8
    max: 27
  
  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2
