seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 2
    time: 1-00:00

# experiment fixed configs (Hyperparameters taken from reported ones in paper)

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false
    seed: 42

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false
      edge_encoder: true
      edge_encoder_name: WeightedSANDummyEdge
      edge_encoder_bn: false

    posenc_WLapPE:
      enable: true
      model: Transformer
      eigen:
        laplacian_norm: sym
        eigvec_norm: L2
        max_freqs: 10
      dim_pe: 16
      layers: 1
      n_heads: 4
      raw_norm_type: none
      post_layers: 0
      pass_as_var: false
      w_add_dummy_edge: true

    train:
      mode: custom
      eval_period: 1
      batch_size: 16

    model:
      type: WeightedSANTransformer
      loss_fun: weighted_cross_entropy

    gt:
      layers: 16
      n_heads: 8
      dim_hidden: 48  # `gt.dim_hidden` must match `gnn.dim_inner`
      full_graph: true
      gamma: 0.1
      gamma_learnable: false
      dropout: 0.0
      layer_norm: false
      batch_norm: true
      residual: true
      attn:
        use_bias: false
        clamp: null

    gnn:
      head: inductive_node
      layers_pre_mp: 0
      layers_post_mp: 3
      dim_inner: 48

    optim:
      optimizer: adam
      weight_decay: 0.0
      base_lr: 0.0005
      max_epoch: 1000
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 10
      min_lr: 1e-5
      early_stopping: true
      early_stopping_patience: 40
      early_stopping_delta_e: 0.02
      early_stopping_warmup: 40

    attack:
      enable: false
