seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 3
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 16G
    cpus-per-task: 4
    time: 1-00:00

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: politifact-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false
      edge_encoder: true
      edge_encoder_name: WeightedSANDummyEdge
      edge_encoder_bn: false

    posenc_WLapPE:
      enable: true
      model: Transformer
      eigen:
        laplacian_norm: sym
        eigvec_norm: L2
      dim_pe: 0  # determined by num_heads_PE and dims per head
      raw_norm_type: none
      post_layers: 0
      pass_as_var: false

    train:
      mode: custom
      batch_size: 32
      eval_period: 1

    model:
      type: WeightedSANTransformer
      loss_fun: cross_entropy

    gt:
      dim_hidden: 0  # determined using num_heads and dims_per_head
      full_graph: true
      gamma_learnable: false
      layer_norm: false
      batch_norm: true
      residual: true
      attn:
        use_bias: false
        clamp: 5.0

    gnn:
      layers_pre_mp: 0
      dim_inner: 0  # determined using num_heads and dims_per_head
    
    optim:
      optimizer: adam
      max_epoch: 250
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 20
      clip_grad_norm: false
      early_stopping: true
      early_stopping_patience: 40
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 40

    attack:
      enable: false

# experiment random configs

random:
  samples: 30
  seed: 1785

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.gnn.head:
    seed: 6938
    type: choice
    options:
      - weighted_mean_pool_graph
      - weighted_add_pool_graph

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 1.0e-5
    max: 5.0e-3

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1.0e-6
    max: 1.0e-3

  graphgym.gt.n_heads:
    seed: 13094
    type: randint
    min: 2
    max: 9

  dims_per_head:
    seed: 164
    type: randint
    min: 2
    max: 11

  graphgym.gt.layers:
    seed: 357
    type: randint
    min: 6
    max: 17

  graphgym.gt.dropout:
    seed: 751
    type: uniform
    min: 0.01
    max: 0.15

  graphgym.gt.wsan_add_dummy_edges:
    seed: 3265
    type: choice
    options:
      - true
      - false

  graphgym.gt.gamma:
    seed: 982
    type: loguniform
    min: 5.0e-4
    max: 2.0e-2

  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2

  graphgym.posenc_WLapPE.eigen.max_freqs:
    seed: 52157
    type: randint
    min: 5
    max: 40

  graphgym.posenc_WLapPE.layers:
    seed: 82
    type: choice
    options:
      - 1
      - 2

  graphgym.posenc_WLapPE.n_heads:
    seed: 235
    type: randint
    min: 2
    max: 7

  dims_per_head_PE:
    seed: 6384
    type: randint
    min: 2
    max: 6
