seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 6
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 2
    time: 1-00:00
    


grid:

  graphgym.pretrained.dir:
    type: choice
    options:
      - '/<your-saved-path>/models/GCN/UPFD_pol_bert/adv/18'  # b: 0.15, k: 4
      - '/<your-saved-path>/models/GCN/UPFD_pol_bert/adv/35'  # b: 0.15, k: 6
      - '/<your-saved-path>/models/GCN/UPFD_pol_bert/adv/8'   # b: 0.15, k: 2
      - '/<your-saved-path>/models/GCN/UPFD_pol_bert/adv/25'  # b: 0.10, k: 5
      - '/<your-saved-path>/models/GCN/UPFD_pol_bert/adv/32'  # b: 0.10, k: 6
      - '/<your-saved-path>/models/GCN/UPFD_pol_bert/adv/34'  # b: 0.10, k: 6

  graphgym.attack.transfer.perturbation_path:
    type: choice
    options:
      - '/<your-saved-path>/perturbations/UPFD_pol_bert/GRIT'
      - '/<your-saved-path>/perturbations/UPFD_pol_bert/SAN'
      - '/<your-saved-path>/perturbations/UPFD_pol_bert/GCN'
      - '/<your-saved-path>/perturbations/UPFD_pol_bert/Graphormer'
      - '/<your-saved-path>/perturbations/UPFD_pol_bert/GPS'
      - '/<your-saved-path>/perturbations/UPFD_pol_bert/Polynormer'

# experiment fixed configs

fixed:

  graphgym:

    out_dir: configs_seml/results

    pretrained:
      finetune: false

    attack:
      transfer:
        enable: true
      enable: true
      num_attacked_graphs: 0
      skip_incorrect_graph_classification: false
      log_progress: false
      load_best_model: false
      split: test
      prediction_level: graph
      remove_isolated_components: true
      run_random_baseline: false
      is_undirected: true
      root_node_idx: 0
      node_injection:
        enable: true
        from_train: true
        from_val: true
        from_test: true
        allow_existing_graph_pert: false
        include_root_nodes: false
        sample_only_trees: true

    # copied from pre-trained model

    accelerator: auto
    benchmark: false
    bn:
      eps: 1.0e-05
      mom: 0.1
    custom_metrics: []
    dataset:
      cache_load: false
      cache_save: false
      dir: ./datasets
      edge_dim: 128
      edge_encoder: false
      edge_encoder_bn: true
      edge_encoder_name: Bond
      edge_encoder_num_types: 0
      edge_message_ratio: 0.8
      edge_negative_sampling_ratio: 1.0
      edge_train_mode: all
      encoder: true
      encoder_bn: true
      encoder_dim: 128
      encoder_name: db
      format: PyG-UPFD
      infer_link_label: null
      label_column: none
      label_table: none
      location: local
      name: politifact-bert
      node_encoder: true
      node_encoder_bn: false
      node_encoder_name: LinearNode
      node_encoder_num_types: 0
      remove_feature: false
      resample_disjoint: false
      resample_negative: false
      shuffle_split: true
      slic_compactness: 10
      split:
      - 0.8
      - 0.1
      - 0.1
      split_dir: ./splits
      split_index: 0
      split_mode: standard
      task: graph
      task_type: classification_binary
      to_undirected: false
      transductive: false
      transform: none
      tu_simple: true
    devices: 1
    example_arg: example
    example_group:
      example_arg: example
    gnn:
      act: relu
      agg: add
      att_final_linear: false
      att_final_linear_bn: false
      att_heads: 1
      batchnorm: true
      clear_feature: true
      dim_inner: 473
      dropout: 0.0
      head: weighted_mean_pool_graph
      keep_edge: 0.5
      l2norm: true
      layer_type: gcnconvweighted
      layers_mp: 2
      layers_post_mp: 3
      layers_pre_mp: 0
      msg_direction: single
      normalize_adj: false
      residual: false
      self_msg: concat
      skip_every: 1
      stage_type: stack
    gpu_mem: false
    mem:
      inplace: false
    metric_agg: argmax
    metric_best: accuracy
    model:
      edge_decoding: dot
      graph_pooling: add
      loss_fun: cross_entropy
      match_upper: true
      size_average: mean
      thresh: 0.5
      type: gnn
    name_tag: ''
    num_threads: 6
    num_workers: 0
    optim:
      base_lr: 0.005286030166148311
      batch_accumulation: 1
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      early_stopping: true
      early_stopping_delta_e: 0.04
      early_stopping_patience: 30
      early_stopping_warmup: 30
      lr_decay: 0.1
      max_epoch: 300
      min_lr: 0.0
      momentum: 0.9
      num_warmup_epochs: 10
      optimizer: adamW
      reduce_factor: 0.1
      schedule_patience: 10
      scheduler: cosine_with_warmup
      steps:
      - 30
      - 60
      - 90
      weight_decay: 0.025931832281559417
    print: both
    round: 5
    run_multiple_splits: []
    share:
      dim_in: 1
      dim_out: 1
      num_splits: 1
    tensorboard_agg: true
    tensorboard_each_run: false
    train:
      auto_resume: false
      batch_size: 16
      ckpt_best: true
      ckpt_clean: true
      ckpt_period: 100
      enable_ckpt: true
      epoch_resume: -1
      eval_period: 1
      iter_per_epoch: 32
      mode: custom
      neighbor_sizes:
      - 20
      - 15
      - 10
      - 5
      node_per_graph: 32
      radius: extend
      sample_node: false
      sampler: full_batch
      skip_train_eval: false
      walk_length: 4
    val:
      node_per_graph: 32
      radius: extend
      sample_node: false
      sampler: full_batch
    view_emb: false
    wandb:
      entity: graph-transformer-robustness
      name: ''
      project: gtblueprint
      use: false
