seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 2
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 24G
    cpus-per-task: 4
    time: 1-00:00

# experiment random configs

random:
  samples: 40
  seed: 1972

  graphgym.seed:
    seed: 7
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 1.0e-4
    max: 5.0e-2

  graphgym.graphormer.num_layers:
   seed: 981
   type: randint
   min: 6
   max: 17

  dims_per_head:
    seed: 13094
    type: randint
    min: 2
    max: 13

  graphgym.graphormer.num_heads:
    seed: 772
    type: randint
    min: 3
    max: 9

  graphgym.graphormer.dropout:
    seed: 961
    type: uniform
    min: 0.0
    max: 0.1
  
  graphgym.graphormer.attention_dropout:
    seed: 661
    type: uniform
    min: 0.0
    max: 0.5

  graphgym.graphormer.mlp_dropout:
    seed: 241
    type: uniform
    min: 0.0
    max: 0.05

  graphgym.gnn.layers_post_mp:
    seed: 821
    type: choice
    options:
      - 1
      - 2

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_bn: false
      edge_encoder: false

    posenc_GraphormerBias:
      enable: true
      node_degrees_only: false
      num_spatial_types: 4
      num_in_degrees: 70
      num_out_degrees: 70
      directed_graphs: false
      has_edge_attr: false
       
 

    train:
      mode: custom
      batch_size: 64
      eval_period: 1
      ckpt_best: true
      enable_ckpt: true

    model:
      type: Graphormer
      loss_fun: cross_entropy

    graphormer:
      use_graph_token: false
      embed_dim: 0
      input_dropout: 0.0

    gnn:
      head: inductive_node
      layers_pre_mp: 0
      dim_inner: 0

    optim:
      optimizer: adam
      weight_decay: 0.0
      max_epoch: 150
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 5
      min_lr: 1.0e-6
      clip_grad_norm: false
      early_stopping: true
      early_stopping_patience: 25
      early_stopping_delta_e: 0.01
      early_stopping_warmup: 40

    attack:
      enable: false
