seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 8
  sbatch_options:
    partition: <slurm-gpu-partition>
    gres: gpu:1
    mem: 32G
    cpus-per-task: 1
    time: 1-00:00

# experiment random configs

random:
  samples: 104
  seed: 1876

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 3.0e-5
    max: 2.0e-2

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1.0e-8
    max: 1.0e-1

  dims_per_head:
    seed: 43514
    type: randint
    min: 4
    max: 9

  graphgym.gt.layers:
    seed: 11762
    type: randint
    min: 3
    max: 13

  graphgym.gnn.layers_post_mp:
    seed: 191
    type: choice
    options:
      - 1
      - 2


# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: gossipcop-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false
      edge_encoder: True
      edge_encoder_name: WeightedDummyEdge
      edge_encoder_bn: False

    train:
      mode: custom
      batch_size: 16

    model:
      type: GPSModel
      loss_fun: cross_entropy

    posenc_WLapPE:
      enable: true
      dim_pe: 16
      layers: 2
      model: DeepSet
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none

    gt:
      layer_type: WeightedGatedGCN+Transformer
      dim_hidden: 0  # determined later
      layer_norm: false
      batch_norm: true
      dropout: 0.1
      attn_dropout: 0.5
      n_heads: 8

    gnn:
      batchnorm: true
      act: relu
      head: weighted_add_pool_graph
      layers_pre_mp: 0
      dim_inner: 0  # determined later

    optim:
      clip_grad_norm: true
      optimizer: adamW
      max_epoch: 100
      scheduler: cosine_with_warmup
      num_warmup_epochs: 5
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.03
      early_stopping_warmup: 15

    attack:
      enable: false
